import { FaSchool, FaUniversity } from "react-icons/fa";
import {
  FaReact,
  FaNodeJs,
  FaPython,
  FaJava,
  FaPhp,
  FaRust,
  FaGitAlt,
  FaDocker,
  FaAws,
  FaHtml5,
  FaCss3Alt,
  FaJsSquare,
  FaComments,
  FaUsers,
  FaLightbulb,
  FaClock,
  FaTasks,
  FaLaravel,
  FaBootstrap,
  FaGithub,
  FaExternalLinkAlt,
  FaCode,
  FaChevronLeft,
  FaChevronRight,
  FaEnvelope,
  FaPhone,
  FaLinkedin,
  FaFacebook,
  FaMapMarkerAlt,
  FaPaperPlane,
} from "react-icons/fa";

import { BsFiletypeSql } from "react-icons/bs";

import {
  SiTypescript,
  SiKotlin,
  SiSwift,
  SiGo,
  SiRuby,
  SiDjango,
  SiFlutter,
  SiMongodb,
  SiPostgresql,
  SiMysql,
  SiTailwindcss,
} from "react-icons/si";

export const Icons = {
  react: FaReact,
  nodejs: FaNodeJs,
  python: FaPython,
  java: FaJava,
  php: FaPhp,
  rust: FaRust,
  git: FaGitAlt,
  docker: FaDocker,
  aws: FaAws,
  html5: FaHtml5,
  css3: FaCss3Alt,
  javascript: FaJsSquare,
  typescript: SiTypescript,
  kotlin: SiKotlin,
  swift: SiSwift,
  go: SiGo,
  ruby: SiRuby,
  django: SiDjango,
  flutter: SiFlutter,
  mongodb: SiMongodb,
  postgresql: SiPostgresql,
  mysql: SiMysql,
  comment: FaComments,
  user: FaUsers,
  problemSolving: FaLightbulb,
  clock: FaClock,
  task: FaTasks,
  laravel: FaLaravel,
  bootstrap: FaBootstrap,
  tailwindcss: SiTailwindcss,
  sqlserver: BsFiletypeSql,
  github: FaGithub,
  link: FaExternalLinkAlt,
  code: FaCode,
  chevronLeft: FaChevronLeft,
  chevronRight: FaChevronRight,

  school: FaSchool,
  university: FaUniversity,

  phone: FaPhone,
  envelope: FaEnvelope,
  linkedIn: FaLinkedin,
  facebook: FaFacebook,
  map: FaMapMarkerAlt,
  plane: FaPaperPlane,
};
